version: '3.8'

services:
  mongo:
    image: mongo:4.4.21
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: turnero
    ports:
      - "8083:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/turnero

volumes:
  mongo_data: